---
micronaut:
    application:
        name: groovylanggorm

---
hibernate:
  hbm2ddl:
    auto: update
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
dataSource:
  url: jdbc:mysql://google/mts_test?socketFactory=com.google.cloud.sql.mysql.SocketFactory&cloudSqlInstance=groovylang:us-west2:open-mts&useSSL=false
  dbCreate: create-update
  pooled: true
  jmxExport: true
  driverClassName: com.mysql.cj.jdbc.Driver
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  username: root
  password: t4jaD40DMOx1s9B0
    # region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
#dataSource:
#  url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
#  pooled: true
#  jmxExport: true
#  driverClassName: org.h2.Driver
#  username: sa
#  password: ''

# open-mts t4jaD40DMOx1s9B0

